-- Revenue Generated by Course and Instructor
-- Calculate the total revenue generated by each course and by each instructor.

-- Revenue by Course
SELECT
    c.course_name,
    SUM(c.price) AS total_revenue
FROM Courses c
JOIN Enrollments e ON c.course_id = e.course_id
WHERE e.status IN ('Completed', 'In Progress') -- Assume payment upon enrollment, or completion
GROUP BY c.course_name
ORDER BY total_revenue DESC;

-- Revenue by Instructor
SELECT
    i.first_name AS instructor_first_name,
    i.last_name AS instructor_last_name,
    SUM(c.price) AS total_revenue_generated
FROM Instructors i
JOIN Courses c ON i.instructor_id = c.instructor_id
JOIN Enrollments e ON c.course_id = e.course_id
WHERE e.status IN ('Completed', 'In Progress')
GROUP BY i.instructor_id, i.first_name, i.last_name
ORDER BY total_revenue_generated DESC;